version: '3.4'

services:
    database:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=default
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=database
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - app_db:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    app_db:
